### ISSUE TITLE
Make code in index.html modular

### ISSUE THREAD

**Issue by parth-paradkar** [creativecommons/cccatalog-dataviz#10]
## Problem Description

Currently, the file `index.html` houses the entire code that defines the display logic of the nodes. However, as new features and components are added, the code will become longer and harder to read. It will also make the HTML file to load slower.

## Solution Description

The code can be broken into modules. All the dependencies of the project are available as `npm` packages. The modules will be bundled into a single `bundle.js` file using `webpack`, which can then be included in `index.html`.

**Comment by parth-paradkar** [comment]
@soccerdroid @mathemancer @kgodey please give your suggestions and views on this.

**Comment by kgodey** [comment]
This sounds good to me. I'd like more detail on what files it should be broken down into.

Also, is this something you want to work on @thescriptninja?

**Comment by parth-paradkar** [comment]
Sure, I'd like to work on this @kgodey, you can assign this to me. I am thinking of splitting in this manner:

- `src/piechart.js` : Contains logic to display piechart. The functions `beautifyLicensename` and `drawPiechart` will be included here.
- `src/graph.js`: Contains logic to display graph i.e fetcing and `traverseHighlight`.
- `src/config.js`: Contains all the configurations. For now, it will have `MAX_FONT_SIZE`, `ending`, `MIN_FONT_SIZE`. We can add more to this later if we like.
- `src/main.js`: imports all the modules.

Webpack will generate a file `dist/bundle.js`, which will the be included in `index.html`.

P.S: 
1. This will entail a change in deploy scripts. For example, I was running `python3 -m http.server 4000` to test locally but now I have to run `webpack --mode=development && python3 -m http.server 4000`.
2. The following additional files will be added: `package.json`, `package-lock.json`, `webpack.config.js`
3. All dependencies will be available as `node_modules`

**Comment by parth-paradkar** [comment]
@kgodey can I start working in this?

**Comment by soccerdroid** [comment]
Hi! @thescriptninja This sounds good to me too. However, do you think you can work this in smaller issues/PRs? We also must let you have time and our repo stable in order for everyone to elaborate their proposals. Please let me know your thoughts or plan about this.

**Comment by parth-paradkar** [comment]
Hi @soccerdroid . Even I thought this is sort of a big change since it involves changing the project structure quite a bit. I was researching a bit and wrote some code in that direction. It seems pretty easy using `webpack` and `babel`.
However, I see your point of keeping the repo stable for the proposals. Maybe we can keep this issue open and make these changes some time later down the line. 

Can you please suggest some other small issues/features I can work on instead?

**Comment by soccerdroid** [comment]
Well, you can work on fixing/adding documentation about the project meanwhile, so people do not get dizzy when they try to run it for the first time. Yes we can leave this issue open because we surely need to work on this. Maybe you can add it to your proposal too, and keep this in mind for your timeline.

**Comment by parth-paradkar** [comment]
Sure @soccerdroid, thanks! I'll look into improving the documentation :+1:
