### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by parth-paradkar** [creativecommons/cccatalog-dataviz#13]
## Problem Description

The current documentation can be improved by adding some more information about the project.

## Solution Description

I will attempt to elaborate on how the current documentation can be extended. 
1. Currently, `/README.md` which is the first piece of documentation that a user faces on visiting the repository, contains very limited information regarding the project. A short paragraph describing the project (which is the first paragraph of `/GSoC2019/README.md`) can be added along with screenshots and a link to the currently deployed webpage.
2. Instructions about how to serve the files in `/GSoC2019/src/` locally needs to be added. I am currently using `python3 -m http.server 4000` to do the same.
3. We can add documentation about the nature of the JSON file in `src/data_processing` (regarding nodes and links).

@soccerdroid @mathemancer @kgodey please provide your views on the same and what else can be added.

I would like to work on this after taking all the suggestions and inputs.

**Comment by kgodey** [comment]
I think this is a good start. Feel free to start work on this and create separate issues for other changes.
