### ISSUE TITLE
Hovering a node does not produce very informative visuals.

### ISSUE THREAD

**Issue by BharatNischal** [creativecommons/cccatalog-dataviz#14]
## Describe the bug

Currently when we hover on a node it highlights all the links which have atleast 1 node as 
1. Hovered node
2. Nodes which can be reached with hovered node as source node
3. Nodes which can be reached from nodes in step 2 as source nodes and so on..

Hovering nodes highlight the specified links. But it is very difficult for a viewer to guess the logic happening behind the scene. Hence it is not soo informative for viewers. (Even I was not able to guess the logic without reading the code). See the screenshots section. 
The more informative logic will be to highlight the source and destination nodes (that are the neighbouring nodes) of the hovered node with different styles for source and destination. For example with different colors. 
## To Reproduce

1. Go to [website](http://dataviz.creativecommons.engineering/)
2. Zoom the website to have a clear view of nodes and links.
3. Hover at different nodes (atleast 7-8 nodes)
4. Can you guess the logic behind the hover-node event ?

## Expected behavior

We should show links where hovered link is source node and where hovered link is destination node with different styles, so that the user should not have to view the direction of link from the link text. Hence making it more informative.

## Screenshots

**Different hovered nodes**

Almost all links are highlighted
![ice_screenshot_20200227-101618](https://user-images.githubusercontent.com/33544814/75889329-c1349780-5e52-11ea-8a5d-b89740eec235.png)

Only 1 link is highlighted
![ice_screenshot_20200227-101838](https://user-images.githubusercontent.com/33544814/75889453-f7721700-5e52-11ea-845c-b17e65b893b4.png)

## Desktop (please complete the following information)
 - OS: Windows 10
 - Browser: Chrome
 - Version: 80

**Comment by BharatNischal** [comment]
@kgodey can I work on this issue?

**Comment by BharatNischal** [comment]
@kgodey  The label "not ready for work" is automatically added. How can I remove it?

**Comment by soccerdroid** [comment]
Hi @BharatNischal . This feature was added in order to check how connected, central or relevant a node is in the graph. This is why the direct neighbors, as well as the neighbors of the neighbors, are highlighted. Though I also see your point that it might be confusing if a node has a lot of connections. I like the idea of having different colors. Do you think you can modify a bit your idea and leave this feature as it is?

**Comment by soccerdroid** [comment]
One idea could be to offer different ways to highlight nodes and having something like a control panel, where the user is able to select suitable options for them to traverse the graph. Maybe you can add this to your proposal.

**Comment by kgodey** [comment]
@BharatNischal All issues are automatically tagged "not ready for work" until a project maintainer reviews it and decides whether we'll accept a PR for the issue.

**Comment by kgodey** [comment]
To answer your question, you cannot remove it, @soccerdroid will remove it once it's ready for you to work on.

**Comment by BharatNischal** [comment]
> Hi @BharatNischal . This feature was added in order to check how connected, central or relevant a node is in the graph. This is why the direct neighbors, as well as the neighbors of the neighbors, are highlighted. Though I also see your point that it might be confusing if a node has a lot of connections. I like the idea of having different colors. Do you think you can modify a bit your idea and leave this feature as it is?

@soccerdroid  How about giving different colors to the outlinks of different nodes. This will keep the feature of how connected a node is and at the same time makes it more informative
Eg
 1 -> [2,3,4] all links in red color
 2 -> [5,6] all links in blue color
 4 -> [7] all links in yellow
and so on
The colors are just example I will choose relevant one.
what you say?

**Comment by BharatNischal** [comment]
> > Hi @BharatNischal . This feature was added in order to check how connected, central or relevant a node is in the graph. This is why the direct neighbors, as well as the neighbors of the neighbors, are highlighted. Though I also see your point that it might be confusing if a node has a lot of connections. I like the idea of having different colors. Do you think you can modify a bit your idea and leave this feature as it is?
> 
> @soccerdroid How about giving different colors to the outlinks of different nodes. This will keep the feature of how connected a node is and at the same time makes it more informative
> Eg
> 1 -> [2,3,4] all links in red color
> 2 -> [5,6] all links in blue color
> 4 -> [7] all links in yellow
> and so on
> The colors are just example I will choose relevant one.
> what you say?

@soccerdroid  If you think its a good solution then please assign me to the issue

**Comment by mathemancer** [comment]
To me, a better way to do this would be to make the edges arrows (rather than plain lines).

**Comment by BharatNischal** [comment]
> To me, a better way to do this would be to make the edges arrows (rather than plain lines).

@soccerdroid  @mathemancer  **I think its a good suggestion. Should I start working on this feature?**
Also Do I include the below suggested feature or not?

> > > Hi @BharatNischal . This feature was added in order to check how connected, central or relevant a node is in the graph. This is why the direct neighbors, as well as the neighbors of the neighbors, are highlighted. Though I also see your point that it might be confusing if a node has a lot of connections. I like the idea of having different colors. Do you think you can modify a bit your idea and leave this feature as it is?
> > 
> > 
> > @soccerdroid How about giving different colors to the outlinks of different nodes. This will keep the feature of how connected a node is and at the same time makes it more informative
> > Eg
> > 1 -> [2,3,4] all links in red color
> > 2 -> [5,6] all links in blue color
> > 4 -> [7] all links in yellow
> > and so on
> > The colors are just example I will choose relevant one.
> > what you say?
> 
> @soccerdroid If you think its a good solution then please assign me to the issue

**Comment by soccerdroid** [comment]
> > To me, a better way to do this would be to make the edges arrows (rather than plain lines).
> 
> @soccerdroid @mathemancer **I think its a good suggestion. Should I start working on this feature?**
> Also Do I include the below suggested feature or not?
> 
> > > > Hi @BharatNischal . This feature was added in order to check how connected, central or relevant a node is in the graph. This is why the direct neighbors, as well as the neighbors of the neighbors, are highlighted. Though I also see your point that it might be confusing if a node has a lot of connections. I like the idea of having different colors. Do you think you can modify a bit your idea and leave this feature as it is?
> > > 
> > > 
> > > @soccerdroid How about giving different colors to the outlinks of different nodes. This will keep the feature of how connected a node is and at the same time makes it more informative
> > > Eg
> > > 1 -> [2,3,4] all links in red color
> > > 2 -> [5,6] all links in blue color
> > > 4 -> [7] all links in yellow
> > > and so on
> > > The colors are just example I will choose relevant one.
> > > what you say?
> > 
> > 
> > @soccerdroid If you think its a good solution then please assign me to the issue

I am not sure if a combination of colors is a solution to the issue. I think @mathemancer suggestion is a good starting point. I'll assign this to you.
