### ISSUE TITLE
Add filtering by nodes to the Linked Commons. (reference idealist)

### ISSUE THREAD

**Issue by mann2108** [creativecommons/cccatalog-dataviz#16]
## Problem Description
 Currently the visualization of the graph is not provide any insights due to large no. of nodes and edges plotted altogether. And also plotting whole graph will create a rendering process too slow.

## Solution Description 
Adding node filter will lead to analyse the particular node with better visualization. The main thing here to focus is that cc dealing with large no. of nodes and links so the time complexity of all the algorithms which are going to implemented must be optimize enough.

So, I came up with an algorithm which will filters the nodes by there domain name and going only  the particular distance as selected by the user with O(N+M) complexity where N,M are the no. of nodes and edges respectively.

1. Every time fetching data from the json file for every filter query is not feasible, so instead we will create graph data structure as user session starts and that data structure will going to use for further filter queries.
That will save time for fetching data every time from json file.

2. Now, I am using the Breadth First Search (BFS) which will traverse the graph level by level and terminate as it reached to the particular distance provided by user. In case distance parameter is missing at that time BFS will traverse till leaf nodes.

3. When the traversal of graph completed that data will passed to forced graph for plotting that's it.

## Snapshots

1. Filter query on domain with autocomplete feature.

![CC_Output_2](https://user-images.githubusercontent.com/44433995/76156926-a189c180-6127-11ea-8495-30834be05708.JPG)

2. Filter nodes by providing traversing depth/distance.

![CC_Output_3](https://user-images.githubusercontent.com/44433995/76156938-d1d16000-6127-11ea-892f-c3bd88a25dd8.jpg)

3. Final Plottings

![CC_Output_1](https://user-images.githubusercontent.com/44433995/76156941-e150a900-6127-11ea-8ff0-bd8f5e452ad7.JPG)

![CC_Output_4](https://user-images.githubusercontent.com/44433995/76156945-ea417a80-6127-11ea-8456-f833c2616860.JPG)

**Comment by BharatNischal** [comment]
@soccerdroid  Since it is a idealist feature, can multiple users work on this? 
or is this meant to be implemented during the code phase only?

**Comment by soccerdroid** [comment]
Hi @BharatNischal , I think this should be included and detailed in your proposal rather than as an open issue. I'd like to know how the data structures you propose  look like, and how will the algorithm work. Nice job! I did not understand your question, could you please rephrase it? 

> @soccerdroid Since it is a idealist feature, can multiple users work on this?
> or is this meant to be implemented during the code phase only?

**Comment by BharatNischal** [comment]
Thanks @soccerdroid, I will include this in my proposal. 

> Hi @BharatNischal , I think this should be included and detailed in your proposal rather than as an open issue. I'd like to know how the data structures you propose look like, and how will the algorithm work. Nice job! I did not understand your question, could you please rephrase it?
> 
> > @soccerdroid Since it is a idealist feature, can multiple users work on this?
> > or is this meant to be implemented during the code phase only?

**Comment by mann2108** [comment]
@soccerdroid So should I close this issue and add this in my proposal? Actually I didn't find any open issue for contribution and contributing is must before applying with proposal. I want you to suggest me some issue so that I can show my sample work.

![Capture1](https://user-images.githubusercontent.com/44433995/76349594-4f67bc80-6330-11ea-9977-ae4357998812.JPG)

**Comment by mann2108** [comment]
> @soccerdroid So should I close this issue and add this in my proposal? Actually I didn't find any open issue for contribution and contributing is must before applying with proposal. I want you to suggest me some issue so that I can show my sample work.
> 
> ![Capture1](https://user-images.githubusercontent.com/44433995/76349594-4f67bc80-6330-11ea-9977-ae4357998812.JPG)

@soccerdroid @kgodey @mathemancer I want your review before I proceed further. I already open a PR for now.

**Comment by kgodey** [comment]
@mann2108 your PR does not have to be merged to count as a contribution. :)

**Comment by mann2108** [comment]
Thank you for letting me know.
