### ISSUE TITLE
Upgrade the version of Force-graph

### ISSUE THREAD

**Issue by BharatNischal** [creativecommons/cccatalog-dataviz#18]
## Problem Description
The version of force-graph currently used in the [Linked Commons](http://dataviz.creativecommons.engineering/) is Version 1.16.1 while the latest version of force-graph is Version 1.26.3.
So some of the useful methods are not available in this version, one of them is **nodeVisibility([boolean, str or fn])** (See the error in the screenshot which says nodeVisibility is not a function).

## Solution Description

Upgrade the force-graph to its latest version so that we can use all the features of this beautiful and powerful library.

## Screenshot
![ice_screenshot_20200312-011833](https://user-images.githubusercontent.com/33544814/76526249-3fb4b900-6493-11ea-9156-30cec6ffaa4f.png)

**Comment by BharatNischal** [comment]
@kgodey  @soccerdroid  Please assign me so that I can update the  [Linked Commons](http://dataviz.creativecommons.engineering/)  with latest version of force-graph.
Although it's a very small change but I think it will help in further development process.

**Comment by soccerdroid** [comment]
Hi @BharatNischal , good catch! But what will happen if the project is moved to a new version? What I mean is that, unless we need functions available in the new version, or if there are critical bugs is the current version we are using, it may not be an issue right now to keep the older version.

**Comment by BharatNischal** [comment]
@soccerdroid I was working on some improvements and found that some of my functions were not working because of older version. So I think it will be right to suggest you to upgrade it but if you wana postpone it for the next version of the Linked Commons I can close the issue.
Should I close this issue

**Comment by soccerdroid** [comment]
Oh ok. Let's leave this issue, and continue working on your improvements. Then you can make a PR and point to this issue.

**Comment by soccerdroid** [comment]
I will assign this to you.

**Comment by BharatNischal** [comment]
@soccerdroid  As also mentioned by **subhamX** in the issue [#19](https://github.com/creativecommons/cccatalog-dataviz/issues/19#issuecomment-601551753) that certain features are not working on the current version of force-graph . So is this the Right time to update it so that he can solve the issue [#19](https://github.com/creativecommons/cccatalog-dataviz/issues/19#issue-583602312) in the easiest way.

**Comment by soccerdroid** [comment]
I'll assign this task to you. Please confirm if you can work on this.

**Comment by BharatNischal** [comment]
@soccerdroid Yes I will surely work on this and will send you a PR soon.
