### ISSUE TITLE
Add a small widget to zoom in and out

### ISSUE THREAD

**Issue by subhamX** [creativecommons/cccatalog-dataviz#19]
## Problem Description
Currently, the page can be zoomed in or out using mouse scrollbar or using trackpad assisted by precision drivers. I feel that adding two small buttons (+ and -) to control zoom level will appeal to most users. The idea is inspired by embedded google maps used by many. (See pic below)

![google_map](https://user-images.githubusercontent.com/43654114/76946919-d0274980-692a-11ea-97ed-0b8888994a48.PNG)
Source - [LINK](https://developers.google.com/maps/documentation/javascript/interaction)

## Solution Description
I am keen to work on this feature. I will create this ```widget``` with position absolute to the viewport and will listen to any click events. On any such event will change the zoom level.

**Comment by subhamX** [comment]
@soccerdroid Please share your thoughts on this enhancement.

**Comment by soccerdroid** [comment]
I think it's a good idea! You'll need to check if this does not collide with force-graph's zooming. I'll assign this to you.

**Comment by subhamX** [comment]
Thank you for assigning this task. :)

I thought of storing the current zoom level and then keep updating it whenever the user interacts with the canvas or programmatically we zoom in. Whenever either of two buttons is clicked by the user relative to this value (Current Zoom Level) I would increment or decrement the zoom level by some specified number.
**Force Graph** comes with a callback function named `onZoomEnd` which is fired on 'end' of zoom/pan events. So effectively we can use this function to keep the stored zoom level updated. But the function wasn't working on the current project. Upon careful observation, I found that the current application is using `v1.16.1` of Force Graph which doesn't have this functionality.

What do you suggest? Should I create a function from scratch or we should integrate this functionality in future after updating the version?

I have created the UI though and here are the snapshots. On hovering the button the text and background colour change slightly. 

![normal_state](https://user-images.githubusercontent.com/43654114/77140495-cecb5d80-6a9f-11ea-8e53-ae68e1f3c55f.PNG)

**Comment by soccerdroid** [comment]
Hi @subhamX ! @BharatNischal updated the library version, so now you can continue with your work.

**Comment by subhamX** [comment]
Great. I will complete this enhancement very soon.
