### ISSUE TITLE
Visualize pie chart while viewing nodes

### ISSUE THREAD

**Issue by ssayima** [creativecommons/cccatalog-dataviz#21]
## Problem Description

When you want to see the description data of a domain and you click on it, the pop-up prevents you from further navigating the graph or seeing the relation between the domain you’re viewing and its neighbouring domains.

## Solution Description

Place the pop-up to the side so that you can still navigate the nodes while viewing the pie chart and node description.

![aside](https://user-images.githubusercontent.com/62557881/77448419-0feda580-6df1-11ea-9bf9-938056c25cb0.png)

**Comment by ssayima** [comment]
Hello, I would really love to work on this feature and hopefully eventually on this project. If you are interested in the idea please assign it to me or anything I can do to contribute for the Outreachy internship application in relation to this project.

**Comment by ssayima** [comment]
Hello, I would really love to work on this feature and hopefully eventually on this project. While a lot of the concepts are new for me its really interesting and I know I will learn it. If you think the proposed change is a good idea please assign it to me or anything I can do to contribute for the Outreachy internship application in relation to this project.

**Comment by subhamX** [comment]
Yes, it will be a useful feature for larger screens. But for medium and smaller screens, it would be tough to navigate the graph and see the pie chart on the sidebar simultaneously. For them, I think the current pop up model will be better.

**Comment by ssayima** [comment]
@subhamX yes I don't think this layout would be mobile friendly but it should improve the experience on most laptops and wider screens. For example this screenshot is from a 1280x800 laptop screen which is on the smaller end and it looks good. Or what do you think of it? Should it apply to all 1024+ wide view port? Or larger? I will leave the mobile version as it is.

**Comment by ssayima** [comment]
Hello @subhamX  here is the proposed changes. I've added a [github pages link](http://ssayima.github.io/cccatalog-dataviz/GSoC2019/src/) for you to test it on multiple screens. Please let me know what you think.

**Comment by ssayima** [comment]
Hello @soccerdroid  here are the proposed changes. I've added a [github pages link](http://ssayima.github.io/cccatalog-dataviz/GSoC2019/src/) for you to test it on multiple screens. Please let me know what you think.
