### ISSUE TITLE
Linked Commons infrastructure updates

### ISSUE THREAD

**Issue by kgodey** [creativecommons/cccatalog-dataviz#36]
- All servers related to this project should be fully deployed via Terraform, including:
  - backend
  - frontend
  - data processing
- There should be **no** dataviz related server resources that are not tracked and launched by Terraform
- There should be an one-click or automated way to deploy both frontend and backend changes to production.
- There should be infrastructure that automatically updates and processes the data in the backend.

**Comment by mathemancer** [comment]
I think this covers it, with the caveat that we may want to have the data processing server be launched by a process on the backend server in some sort of monthly job fashion.  So, it may be that it's not defined by terraform, but rather an EC2 definition JSON that would be in the repo.  What do you think, @kgodey ?

**Comment by kgodey** [comment]
@mathemancer that sounds fine to me, the main thing I care about that all of the infrastructure is in code somewhere and that there are no manual steps

**Comment by mathemancer** [comment]
Closing this for now.  We'll take a new look in 2021.
