### ISSUE TITLE
Create permanent deployment for the data visualization

### ISSUE THREAD

**Issue by kgodey** [creativecommons/cccatalog-dataviz#5]
Should use Terraform to provision.

It would be great if we could automatically update it when we had new Common Crawl data but that can be separated into its own issue.

**Comment by aldenstpage** [comment]
It's been Terraform'd and is live at http://dataviz.creativecommons.engineering.

https://github.com/creativecommons/ccsearch-infrastructure/commit/24f5506e369f2eb5eaa8b128667ad3257083df07
