### ISSUE TITLE
The close button in the Linked Commons is not visible.

### ISSUE THREAD

**Issue by BharatNischal** [creativecommons/cccatalog-dataviz#6]
## Describe the bug
The close button on the  [Linked Common](http://dataviz.creativecommons.engineering/) website which should appear in the popup screen after clicking on a node (having some license information) is not visible on the deployed version. So once the user has clicked a node he is unable to close the details/ piechart modal of the node.

## To Reproduce
1. Go to [Linked Common website](http://dataviz.creativecommons.engineering/)
2. Click on 'any node'
3. If the popup window says no information for the given license. Then close the node and select some other node with some information.
4. Error 'There is no close button to go back to the starting screen'.

## Expected behavior
The close button should be visible to the user so he/she can go back to the graph screen.

## Screenshots
![ice_screenshot_20200224-231053](https://user-images.githubusercontent.com/33544814/75178669-8a79c580-575e-11ea-8e33-1ac4bd8b0108.png)
Screenshot on chrome browser with no close button.
![ice_screenshot_20200224-231021](https://user-images.githubusercontent.com/33544814/75178740-ae3d0b80-575e-11ea-8fd5-de27d66dd27f.png)
Screenshot on firefox with no close button.

## Desktop 
 - OS: windows 10
 - Browser Chrome, Firefox
 - Version Chrome v79.0, Firefox 73.0.1

## Additional context
I will like to solve this issue. So please assign me this issue.

**Comment by BharatNischal** [comment]
I will like to solve this issue. As I had found the reason for the problem of this unexpected behaviour and will like to solve it as soon as it is assigned to me.

**Comment by kgodey** [comment]
@BharatNischal go ahead and work on this.

This bug depends on screen size; it works on my screen. Keep that in mind while working on it.
